<?php

declare(strict_types=1);

/**
 * This file is part of the RealpadTakeout package
 *
 * https://github.com/Spoje-NET/PHP-Realpad-Takeout
 *
 * (c) Spoje.Net IT s.r.o. <http://spojenenet.cz/>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Tests;

use PHPUnit\Framework\TestCase;

/**
 * Tests for MultiFlexi report format compliance.
 */
class ReportFormatTest extends TestCase
{
    /**
     * Test that the report format conforms to MultiFlexi schema.
     */
    public function testReportFormatConformsToMultiFlexiSchema(): void
    {
        // Sample report structure as it should be generated by the application
        $report = [
            'status' => 'success',
            'timestamp' => (new \DateTime())->format(\DateTime::ATOM),
            'message' => 'Payment registered successfully',
            'artifacts' => [
                'realpad_endpoint' => ['https://cms.realpad.eu/ws/v10/add-payments-pohoda'],
                'pohoda_xml' => ['/tmp/Bankovni_doklady.xml'],
                'realpad_response' => ['/tmp/realpad_response_abc123.txt']
            ],
            'metrics' => [
                'payments_processed' => 1,
                'http_response_code' => 201,
                'pohoda_records_found' => 5,
                'exit_code' => 0
            ]
        ];

        // Test required fields
        $this->assertArrayHasKey('status', $report, 'Report must have status field');
        $this->assertArrayHasKey('timestamp', $report, 'Report must have timestamp field');

        // Test status field values
        $this->assertContains(
            $report['status'],
            ['success', 'error', 'warning'],
            'Status must be one of: success, error, warning'
        );

        // Test timestamp format (ISO8601)
        $this->assertMatchesRegularExpression(
            '/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}[+-]\d{2}:\d{2}$/',
            $report['timestamp'],
            'Timestamp must be in ISO8601 format'
        );

        // Test optional fields structure
        if (isset($report['message'])) {
            $this->assertIsString($report['message'], 'Message must be a string');
        }

        if (isset($report['artifacts'])) {
            $this->assertIsArray($report['artifacts'], 'Artifacts must be an array');
            
            foreach ($report['artifacts'] as $artifactType => $artifactList) {
                $this->assertIsString($artifactType, 'Artifact type must be a string');
                $this->assertIsArray($artifactList, 'Artifact list must be an array');
                
                foreach ($artifactList as $artifact) {
                    $this->assertIsString($artifact, 'Each artifact must be a string');
                }
            }
        }

        if (isset($report['metrics'])) {
            $this->assertIsArray($report['metrics'], 'Metrics must be an array');
            
            foreach ($report['metrics'] as $metricName => $metricValue) {
                $this->assertIsString($metricName, 'Metric name must be a string');
                $this->assertTrue(
                    is_numeric($metricValue) || is_string($metricValue),
                    'Metric value must be numeric or string'
                );
            }
        }

        // Validate JSON encoding
        $json = json_encode($report);
        $this->assertNotFalse($json, 'Report must be JSON encodable');

        $decoded = json_decode($json, true);
        $this->assertEquals($report, $decoded, 'Report must survive JSON encode/decode cycle');
    }

    /**
     * Test error report format.
     */
    public function testErrorReportFormat(): void
    {
        $report = [
            'status' => 'error',
            'timestamp' => (new \DateTime())->format(\DateTime::ATOM),
            'message' => 'Unauthorized: Invalid credentials or banned account/IP.',
            'artifacts' => [
                'realpad_endpoint' => ['https://cms.realpad.eu/ws/v10/add-payments-pohoda']
            ],
            'metrics' => [
                'payments_processed' => 0,
                'http_response_code' => 401,
                'pohoda_records_found' => 0,
                'exit_code' => 401
            ]
        ];

        $this->assertEquals('error', $report['status']);
        $this->assertIsString($report['message']);
        $this->assertEquals(0, $report['metrics']['payments_processed']);
        $this->assertEquals(401, $report['metrics']['http_response_code']);
    }

    /**
     * Test warning report format.
     */
    public function testWarningReportFormat(): void
    {
        $report = [
            'status' => 'warning',
            'timestamp' => (new \DateTime())->format(\DateTime::ATOM),
            'message' => 'Payment already exists. ID: mock-existing-payment-id-1234',
            'artifacts' => [
                'realpad_endpoint' => ['https://cms.realpad.eu/ws/v10/add-payments-pohoda'],
                'pohoda_xml' => ['/tmp/Bankovni_doklady.xml'],
                'realpad_response' => ['/tmp/realpad_response_def456.txt']
            ],
            'metrics' => [
                'payments_processed' => 0,
                'http_response_code' => 200,
                'pohoda_records_found' => 3,
                'exit_code' => 0
            ]
        ];

        $this->assertEquals('warning', $report['status']);
        $this->assertIsString($report['message']);
        $this->assertEquals(0, $report['metrics']['payments_processed']);
        $this->assertEquals(200, $report['metrics']['http_response_code']);
    }
}